cd_sheets = {
    'ti': {}
}

a = [{'column': 'FY19 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY20 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY21 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY22 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY23 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY24 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY25 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY26 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY27 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY28 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}},
 {'column': 'FY29 Talent',
  'rules': {'Top Talent': '#63be7b',
   'Emerging Talent': '#ffeb84',
   'Solid Talent': '#bfbfbf'}}]